### ISSUE TITLE
deprecate and archive in favor of go-ipld-prime

### ISSUE THREAD

**Issue by mvdan** [ipld/go-ipld-schema#18]
Now that we finished https://github.com/ipld/go-ipld-prime/issues/188 (see the `schema/dsl` and `schema/dmt` packages) I think we should deprecate this module and archive the repo, much like we did with go-ipld-prime-proto in favor of go-codec-dagpb.

There's no harm in keeping the code online, but the deprecation and archiving would help avoid confusion among users, and would ensure that developers don't spend time making improvements here if most of the effort should be on the other packages instead.

@warpfork @rvagg thoughts? Like with go-ipld-prime-proto, I'm more than happy to do the setup work if @warpfork can press the "archive" button as the last step.

**Comment by rvagg** [comment]
+1

**Comment by rvagg** [comment]
Archiving this repo
